### ISSUE TITLE
docker容器异常退出

### ISSUE THREAD

**Issue by Bronya-Rayi** [MT-Photos/mt-photos-ai#3]
在执行ocr命令时，占用内存会突然增大，最后导致容器卡死退出，没有报错日志
环境为ubuntu20.04 4h8g虚拟机跑的docker，讲道理这配置不算差了
![image](https://github.com/MT-Photos/mt-photos-ai/assets/47048823/321905ee-f76e-4b1e-ac5c-36c9f457b719)

**Comment by tza17313** [comment]
换 onnx-latest tag的镜像，内存占用会小一些；
